Portfolio: setup and mobile first
Danny-imo/my-project pull request #1
Opened 2023-06-02 22:03 UTC by Danny-imo

### **In This Milestone**

1. Use images and backgrounds to enhance the look of the website.
2. Build a personal portfolio site.
3. Use responsive values in your CSS rules, like percentages (i.e. width: 80%), instead of pixels

2023-06-02 22:44 UTC, stanleySimeon requested changes
# Hi @Danny-imo, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://media4.giphy.com/media/fQfSfrABMzaGMI6PR2/giphy-downsized.gif?cid=29caca75gpeopdt7l9sxgwk3ws2oooiguj6g9o6pnod67wfe&ep=v1_gifs_search&rid=giphy-downsized.gif&ct=g)

## Highlights
- Correct use of Gitflow ✔️
- Linter checks are passed ✔️
- Good PR description ✔️
- Meaningful commit messages ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- adding your live demo link.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-02 22:44 UTC, stanleySimeon commented on README.md
> +This project is [MIT](./MIT.md) licensed.
Kindly make sure this link works and redirects to the MIT license. 
<img width="1112" alt="Screenshot 2023-06-02 at 6 25 02 PM" src="https://github.com/Danny-imo/my-project/assets/91237525/372fc618-b87c-4018-9c67-d24cc190cce3">

2023-06-02 22:44 UTC, stanleySimeon commented on index.html
> +    </nav>
- Kindly, I suggest you make sure that the container of the header section is a `header` tag.
- Kindly, make sure the logo is inside a link `a` tag.
- [OPTIONAL] Please, make sure you have descriptive `classes` in your code base to follow HTML best practices and not by following that your CSS file will be easy to read by another developer and code reviewer, and your project will look more professional.

2023-06-02 22:44 UTC, stanleySimeon commented on index.html
> +<h2 class="intro">I'm Daniel glad to see you</h2>
Kindly, I suggest you use the `h1` tag instead of `h2` for the first heading to follow HTML best practices. 😄

2023-06-02 22:44 UTC, stanleySimeon commented on index.html
> +    <p class="social">LET'S CONNECT</p>
Kindly, I suggest you use an 'h2` tag for this header instead of a `p` tag for best practice reasons. 😄

2023-06-02 22:44 UTC, stanleySimeon commented on index.html
> +    </ul>
Great work so far, but make sure that each icon has a link (`a` tag).
Apart from being semantically correct, the `a` tag will let you connect your social networks with the icons, using href. 😄

2023-06-03 00:24 UTC, roshan-bajgain requested changes
Hi @Danny-imo, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Good job on implementing some changes ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 00:24 UTC, roshan-bajgain commented on index.html
> +<h2 class="intro1">I’m a software developer! I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and have a project you need code
- [ ] As you were not clear about the suggestion, this is the content of the page or paragraph so we use `p` tag for the pagagraph. Please replace this `h2` tag with `p` tag.

2023-06-03 00:24 UTC, roshan-bajgain commented on index.html
> +    <p class="social">LET'S CONNECT</p>
- [ ] The previous reviewer was giving feedback about this sub-heading as we use `h2` tag for the sub-heading for better semantic resason.

2023-06-03 00:24 UTC, roshan-bajgain commented on index.html
> +<h2 class="intro1">I’m a software developer! I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and have a project you need code
- [ ] [Optional] You should stick to the design as much as possible I would suggest you please adjust the spacing by looking at the Figma design. The logo should be on the right of the page as there is more gap. Please fix it and If you see the Figma design then you will find equal spacing from left and right but you have no spacing from left. Please fix it.
### Your design
![his](https://github.com/Danny-imo/my-project/assets/81727988/7ca25a2f-85f1-48ba-9deb-8d363af455b1)

### Figma design
![fimga](https://github.com/Danny-imo/my-project/assets/81727988/c4dcf58b-3222-493a-8f3e-d8c1aa579293)

2023-06-03 00:24 UTC, roshan-bajgain commented on index.html
> +<h2 class="intro1">I’m a software developer! I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and have a project you need code
- [ ] [Optional] You should stick to the design as much as possible I would suggest you please adjust the spacing by looking at the Figma design. The logo should be on the right of the page as there is more gap. Please fix it and If you see the Figma design then you will find equal spacing from left and right but you have no spacing from left. Please fix it.
### Your design
![his](https://github.com/Danny-imo/my-project/assets/81727988/7ca25a2f-85f1-48ba-9deb-8d363af455b1)

### Figma design
![fimga](https://github.com/Danny-imo/my-project/assets/81727988/c4dcf58b-3222-493a-8f3e-d8c1aa579293)

2023-06-03 00:24 UTC, roshan-bajgain commented on index.html
> +<h2 class="intro1">I’m a software developer! I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and have a project you need code
- [ ] [Optional] You should stick to the design as much as possible I would suggest you please adjust the spacing by looking at the Figma design. The logo should be on the right of the page as there is more gap. Please fix it and If you see the Figma design then you will find equal spacing from left and right but you have no spacing from left. Please fix it.
### Your design
![his](https://github.com/Danny-imo/my-project/assets/81727988/7ca25a2f-85f1-48ba-9deb-8d363af455b1)

### Figma design
![fimga](https://github.com/Danny-imo/my-project/assets/81727988/c4dcf58b-3222-493a-8f3e-d8c1aa579293)

2023-06-03 10:34 UTC, KanzaTahreem approved these changes
# Approved 🥳

Hi @Danny-imo 

Great work implanting the changes suggested by previous reviewers 💪 **_Your project is COMPLETE! There is nothing else to say other than... it's time to merge it! 🚀 Congratulations!_**

<img src="https://media4.giphy.com/media/cFkiFMDg3iFoI/giphy.gif"/>

## Highlights 🎯
There are some excellent points that you have made perfectly. Keep up the great work! 👏

-  ✅ Styling is looking great, perfect!
-  ✅ Great work using the right GitHub Flow 
-  ✅ Your README looks good, well done!
-  ✅ Linters are working properly, great job! 

## Optional suggestions ❕
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

N/A

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 12:31 UTC, merged